# Generated by Django 5.0.6 on 2024-07-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_announcement_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headliner',
            name='date_created',
        ),
        migrations.AddField(
            model_name='headliner',
            name='src',
            field=models.CharField(default='/', max_length=128, verbose_name='Source URL'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='public/announcements/', verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='headliner',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='headliner',
            name='title_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='headliner',
            name='title_kk',
            field=models.CharField(max_length=64, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='headliner',
            name='title_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Title'),
        ),
    ]
