# Generated by Django 5.0.6 on 2024-08-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_alter_vacancy_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-date_created',), 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date_created',), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date_created',), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ('-date_created',), 'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
