# Generated by Django 5.0.6 on 2024-08-12 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_alter_announcement_options_alter_event_options_and_more'),
        ('university', '0009_remove_personal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='university.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='university.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='news',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='university.department', verbose_name='Department'),
        ),
    ]
