# Generated by Django 5.0.6 on 2024-08-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_program_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='name_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='program',
            name='name_kk',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='program',
            name='name_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
    ]
