# Generated by Django 5.0.6 on 2024-09-10 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_program_name_en_program_name_kk_program_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headliner',
            options={'ordering': ('order',), 'verbose_name': 'Headliner', 'verbose_name_plural': 'Headliners'},
        ),
    ]
