# Generated by Django 5.0.6 on 2024-09-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_alter_headliner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('file', models.FileField(blank=True, null=True, upload_to='public/journals/', verbose_name='File')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Partner name')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='public/journals/', verbose_name='Poster')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ('order',),
            },
        ),
    ]
