# Generated by Django 5.0.6 on 2024-09-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_journal_poster_alter_partner_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('order',), 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AddField(
            model_name='program',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
