# Generated by Django 5.0.6 on 2024-10-17 05:13

import django.db.models.deletion
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0017_alter_announcement_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='public/events/', validators=[main.validators.validate_file_size], verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='headliner',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='public/headliners/', validators=[main.validators.validate_file_size], verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='public/journals/', validators=[main.validators.validate_file_size], verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='news',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='public/news/', validators=[main.validators.validate_file_size], verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='public/partners/', validators=[main.validators.validate_file_size], verbose_name='Poster'),
        ),
        migrations.CreateModel(
            name='AnnouncementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='public/announcement/files/', validators=[main.validators.validate_file_size], verbose_name='File')),
                ('own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.announcement', verbose_name='Announcement')),
            ],
            options={
                'verbose_name': 'Announcement file',
                'verbose_name_plural': 'Announcement files',
            },
        ),
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='public/events/files/', validators=[main.validators.validate_file_size], verbose_name='File')),
                ('own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event file',
                'verbose_name_plural': 'Event files',
            },
        ),
        migrations.CreateModel(
            name='NewsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='public/news/files/', validators=[main.validators.validate_file_size], verbose_name='File')),
                ('own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.news', verbose_name='News')),
            ],
            options={
                'verbose_name': 'News file',
                'verbose_name_plural': 'News files',
            },
        ),
    ]
