# Generated by Django 5.0.6 on 2024-10-17 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0018_alter_event_poster_alter_headliner_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfile',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='announcementfile',
            name='own',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_files', to='public.announcement', verbose_name='Announcement'),
        ),
        migrations.AlterField(
            model_name='eventfile',
            name='own',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_files', to='public.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='newsfile',
            name='own',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_files', to='public.news', verbose_name='News'),
        ),
    ]
