# Generated by Django 5.0.6 on 2024-10-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0019_newsfile_title_alter_announcementfile_own_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementfile',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='eventfile',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='Title'),
        ),
    ]
