# Generated by Django 5.0.6 on 2024-11-05 07:06

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0020_announcementfile_title_eventfile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='public/events/', validators=[main.validators.validate_poster], verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='headliner',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='public/headliners/', validators=[main.validators.validate_poster], verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='news',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='public/news/', validators=[main.validators.validate_poster], verbose_name='Poster'),
        ),
    ]
