# Generated by Django 5.0.6 on 2024-12-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0021_alter_event_poster_alter_headliner_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='url',
            field=models.URLField(default='', max_length=128, verbose_name='URL'),
        ),
    ]
