# Generated by Django 5.0.6 on 2024-12-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0022_specialty_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='url',
            field=models.URLField(blank=True, max_length=128, null=True, verbose_name='URL'),
        ),
    ]
