# Generated by Django 5.0.6 on 2025-02-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0024_remove_specialty_program_delete_program_and_more'),
        ('university', '0059_alter_faculty_options_faculty_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Warning! This field is not relevant for faculties and departments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_announcements', to='university.division', verbose_name='Division'),
        ),
        migrations.AddField(
            model_name='event',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Warning! This field is not relevant for faculties and departments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_events', to='university.division', verbose_name='Division'),
        ),
        migrations.AddField(
            model_name='news',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Warning! This field is not relevant for faculties and departments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_news', to='university.division', verbose_name='Division'),
        ),
    ]
