# Generated by Django 5.0.6 on 2025-02-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0026_pageview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageview',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='page_url',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='user',
        ),
        migrations.AddField(
            model_name='pageview',
            name='auth_users_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Auth users count'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='users_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Users count'),
        ),
    ]
