# Generated by Django 5.0.6 on 2025-02-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0027_remove_pageview_ip_address_remove_pageview_page_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='pathname',
            field=models.CharField(default=1, max_length=255, verbose_name='Pathname'),
            preserve_default=False,
        ),
    ]
