# Generated by Django 5.0.6 on 2025-03-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0028_pageview_pathname'),
    ]

    operations = [
        migrations.AddField(
            model_name='headliner',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='Is archive'),
        ),
    ]
