# Generated by Django 5.0.6 on 2024-07-21 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.category', verbose_name='Subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('file', models.FileField(upload_to='category/contents/files/', verbose_name='File')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_contents', to='content.content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'File content',
                'verbose_name_plural': 'File contents',
                'ordering': ('-index',),
            },
        ),
        migrations.CreateModel(
            name='PopupContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popup_contents', to='content.content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'According content',
                'verbose_name_plural': 'According contents',
                'ordering': ('-index',),
            },
        ),
        migrations.CreateModel(
            name='StaffContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Image')),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_contents', to='content.content', verbose_name='Content')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Staff content',
                'verbose_name_plural': 'Staff contents',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_contents', to='content.content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Text content',
                'verbose_name_plural': 'Text contents',
                'ordering': ('-index',),
            },
        ),
    ]
