# Generated by Django 5.0.6 on 2024-07-29 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_kk', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('app_name', models.CharField(choices=[('content', 'Content app'), ('university', 'University app')], default='content', verbose_name='App name')),
                ('multiple', models.BooleanField(default=False, verbose_name='Multiple')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.category', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255, verbose_name='Caption')),
                ('caption_ru', models.CharField(max_length=255, null=True, verbose_name='Caption')),
                ('caption_kk', models.CharField(max_length=255, null=True, verbose_name='Caption')),
                ('caption_en', models.CharField(max_length=255, null=True, verbose_name='Caption')),
                ('file', models.FileField(upload_to='content/category/files/', verbose_name='File')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_contents', to='content.content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'File content',
                'verbose_name_plural': 'File contents',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='PopupContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=255, verbose_name='Trigger')),
                ('trigger_ru', models.CharField(max_length=255, null=True, verbose_name='Trigger')),
                ('trigger_kk', models.CharField(max_length=255, null=True, verbose_name='Trigger')),
                ('trigger_en', models.CharField(max_length=255, null=True, verbose_name='Trigger')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popup_contents', to='content.content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Popup content',
                'verbose_name_plural': 'Popup contents',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='StaffContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/category/staff/', verbose_name='Image')),
                ('profession', models.CharField(max_length=255, verbose_name='Profession')),
                ('profession_ru', models.CharField(max_length=255, null=True, verbose_name='Profession')),
                ('profession_kk', models.CharField(max_length=255, null=True, verbose_name='Profession')),
                ('profession_en', models.CharField(max_length=255, null=True, verbose_name='Profession')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_ru', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_kk', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_en', models.TextField(blank=True, null=True, verbose_name='About')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_contents', to='content.content', verbose_name='Content')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Staff content',
                'verbose_name_plural': 'Staff contents',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_contents', to='content.content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Text content',
                'verbose_name_plural': 'Text contents',
                'ordering': ('index',),
            },
        ),
    ]
