# Generated by Django 5.0.6 on 2024-07-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='target',
            field=models.BooleanField(default=False, verbose_name='Target'),
        ),
        migrations.AlterField(
            model_name='category',
            name='app_name',
            field=models.CharField(choices=[('none', 'None'), ('content', 'Content app'), ('university', 'University app')], default='none', verbose_name='App name'),
        ),
    ]
