# Generated by Django 5.0.6 on 2024-07-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_chapter_name_en_chapter_name_kk_chapter_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='according',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='file',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='text',
            name='chapter',
        ),
    ]
