# Generated by Django 5.0.6 on 2024-07-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_textcontent_body_en_textcontent_body_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontent',
            name='caption_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='filecontent',
            name='caption_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='filecontent',
            name='caption_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Caption'),
        ),
    ]
