# Generated by Django 5.0.6 on 2024-07-21 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_category_name_alter_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='filecontent',
            options={'ordering': ('index',), 'verbose_name': 'File content', 'verbose_name_plural': 'File contents'},
        ),
        migrations.AlterModelOptions(
            name='popupcontent',
            options={'ordering': ('index',), 'verbose_name': 'Popup content', 'verbose_name_plural': 'Popup contents'},
        ),
        migrations.AlterModelOptions(
            name='textcontent',
            options={'ordering': ('index',), 'verbose_name': 'Text content', 'verbose_name_plural': 'Text contents'},
        ),
        migrations.RemoveField(
            model_name='filecontent',
            name='title',
        ),
        migrations.RemoveField(
            model_name='popupcontent',
            name='title',
        ),
        migrations.AddField(
            model_name='filecontent',
            name='caption',
            field=models.CharField(default=1, max_length=255, verbose_name='Caption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popupcontent',
            name='trigger',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Trigger'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/contents/staff/', verbose_name='Image'),
        ),
    ]
