# Generated by Django 5.0.6 on 2024-07-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_category_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='app_name',
            field=models.CharField(choices=[('content', 'Content app'), ('university', 'University app')], default='Content app', verbose_name='App name'),
        ),
    ]
