# Generated by Django 5.0.6 on 2024-08-08 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_contentitem_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=128, verbose_name='Profession')),
                ('profession_ru', models.CharField(max_length=128, null=True, verbose_name='Profession')),
                ('profession_kk', models.CharField(max_length=128, null=True, verbose_name='Profession')),
                ('profession_en', models.CharField(max_length=128, null=True, verbose_name='Profession')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('bio_ru', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('bio_kk', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='content.content', verbose_name='Content')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Staff content',
                'verbose_name_plural': 'Staff contents',
            },
        ),
    ]
