# Generated by Django 5.0.6 on 2024-08-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_staffcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffcontent',
            name='user',
        ),
        migrations.AddField(
            model_name='staffcontent',
            name='full_name',
            field=models.CharField(default=1, max_length=128, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffcontent',
            name='full_name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='staffcontent',
            name='full_name_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='staffcontent',
            name='full_name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='staffcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/category/staff/', verbose_name='Image'),
        ),
    ]
