# Generated by Django 5.0.6 on 2024-07-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_category_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='app_name',
            field=models.CharField(choices=[('content', 'Content app'), ('university', 'University app')], default='content', verbose_name='App name'),
        ),
    ]
