# Generated by Django 5.0.6 on 2024-08-08 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_staffcontent_user_staffcontent_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_contents', to='content.content', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='imagecontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_contents', to='content.content', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='staffcontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_contents', to='content.content', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_contents', to='content.content', verbose_name='Content'),
        ),
        migrations.DeleteModel(
            name='ContentItem',
        ),
    ]
