# Generated by Django 5.0.6 on 2024-07-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_category_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='content',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='content',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='content',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='content',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='content',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='filecontent',
            name='caption_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='filecontent',
            name='caption_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='filecontent',
            name='caption_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='popupcontent',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='popupcontent',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='popupcontent',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='popupcontent',
            name='trigger_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Trigger'),
        ),
        migrations.AddField(
            model_name='popupcontent',
            name='trigger_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Trigger'),
        ),
        migrations.AddField(
            model_name='popupcontent',
            name='trigger_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Trigger'),
        ),
        migrations.AddField(
            model_name='staffcontent',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='staffcontent',
            name='about_kk',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='staffcontent',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='staffcontent',
            name='profession_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='staffcontent',
            name='profession_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='staffcontent',
            name='profession_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
