# Generated by Django 5.0.6 on 2024-07-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_content_description_en_content_description_kk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('index',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
