# Generated by Django 5.0.6 on 2024-07-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='multiple',
            field=models.BooleanField(default=False, verbose_name='Multiple'),
        ),
    ]
