# Generated by Django 5.0.6 on 2024-08-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_staffcontent_call_staffcontent_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffcontent',
            name='call',
        ),
        migrations.RemoveField(
            model_name='staffcontent',
            name='room',
        ),
    ]
