# Generated by Django 5.0.6 on 2024-08-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_staffcontent_call_remove_staffcontent_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='URL'),
        ),
    ]
