# Generated by Django 5.0.6 on 2024-07-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_category_multiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontent',
            name='file',
            field=models.FileField(upload_to='content/category/files/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='staffcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/category/staff/', verbose_name='Image'),
        ),
    ]
