# Generated by Django 5.0.6 on 2024-08-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcontent',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='staffcontent',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone'),
        ),
    ]
