# Generated by Django 5.0.6 on 2024-08-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_staffcontent_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffcontent',
            options={'ordering': ('order',), 'verbose_name': 'Staff content', 'verbose_name_plural': 'Staff contents'},
        ),
    ]
