# Generated by Django 5.0.6 on 2024-11-05 07:06

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_staffcontent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/category/staff/', validators=[main.validators.validate_logo], verbose_name='Image'),
        ),
    ]
