# Generated by Django 5.0.6 on 2024-11-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_staffcontent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecontent',
            name='image_en',
            field=models.ImageField(null=True, upload_to='content/category/images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='imagecontent',
            name='image_kk',
            field=models.ImageField(null=True, upload_to='content/category/images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='imagecontent',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='content/category/images/', verbose_name='Image'),
        ),
    ]
