# Generated by Django 5.0.6 on 2025-01-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_imagecontent_image_en_imagecontent_image_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontent',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='content/category/source_files/', verbose_name='Source file'),
        ),
        migrations.AddField(
            model_name='filecontent',
            name='source_file_en',
            field=models.FileField(blank=True, null=True, upload_to='content/category/source_files/', verbose_name='Source file'),
        ),
        migrations.AddField(
            model_name='filecontent',
            name='source_file_kk',
            field=models.FileField(blank=True, null=True, upload_to='content/category/source_files/', verbose_name='Source file'),
        ),
        migrations.AddField(
            model_name='filecontent',
            name='source_file_ru',
            field=models.FileField(blank=True, null=True, upload_to='content/category/source_files/', verbose_name='Source file'),
        ),
    ]
