# Generated by Django 5.0.6 on 2025-01-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_filecontent_source_file_filecontent_source_file_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontent',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='content/category/files/', verbose_name='Source file'),
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='source_file_en',
            field=models.FileField(blank=True, null=True, upload_to='content/category/files/', verbose_name='Source file'),
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='source_file_kk',
            field=models.FileField(blank=True, null=True, upload_to='content/category/files/', verbose_name='Source file'),
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='source_file_ru',
            field=models.FileField(blank=True, null=True, upload_to='content/category/files/', verbose_name='Source file'),
        ),
    ]
