# Generated by Django 5.0.6 on 2025-01-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_filecontent_source_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filecontent',
            options={'ordering': ('order',), 'verbose_name': 'File content', 'verbose_name_plural': 'File contents'},
        ),
        migrations.AlterModelOptions(
            name='imagecontent',
            options={'ordering': ('order',), 'verbose_name': 'Image content', 'verbose_name_plural': 'Image contents'},
        ),
        migrations.AlterModelOptions(
            name='textcontent',
            options={'ordering': ('order',), 'verbose_name': 'Text content', 'verbose_name_plural': 'Text contents'},
        ),
        migrations.AddField(
            model_name='filecontent',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='imagecontent',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
