# Generated by Django 5.0.6 on 2025-01-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_alter_filecontent_options_alter_imagecontent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filecontent',
            name='file',
        ),
    ]
