# Generated by Django 5.0.6 on 2025-01-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_remove_filecontent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontent',
            name='caption',
            field=models.CharField(max_length=360, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='caption_en',
            field=models.CharField(max_length=360, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='caption_kk',
            field=models.CharField(max_length=360, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='caption_ru',
            field=models.CharField(max_length=360, null=True, verbose_name='Caption'),
        ),
    ]
