# Generated by Django 5.0.6 on 2024-07-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_name_kk_category_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Topic name'),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Topic name'),
        ),
    ]
