# Generated by Django 5.0.6 on 2024-07-04 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_topic_name_kk_topic_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
