# Generated by Django 5.0.6 on 2024-07-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_chapter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Chapter name'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Chapter name'),
        ),
    ]
