# Generated by Django 5.0.6 on 2024-07-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chapter_name_kk_chapter_name_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-index',), 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='category',
        ),
    ]
