# Generated by Django 5.0.6 on 2024-07-04 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_topic_options_remove_chapter_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('-index',), 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sub category name')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Sub category',
                'verbose_name_plural': 'Sub categories',
                'ordering': ('index',),
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subcategory', verbose_name='Sub category'),
        ),
    ]
