# Generated by Django 5.0.6 on 2024-07-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_chapter_options_subcategory_topic_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Sub category name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sub category name'),
        ),
    ]
