# Generated by Django 5.0.6 on 2024-07-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_subcategory_name_kk_subcategory_name_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
