# Generated by Django 5.0.6 on 2024-07-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_topic_sub_category_delete_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('content_type', models.CharField(choices=[('TXT', 'Is text content'), ('FL', 'Is file content'), ('IMG', 'Is image content'), ('ALL', 'Is all content')], default='Is text content', verbose_name='Content type')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chapter', verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ('-index',),
            },
        ),
    ]
