# Generated by Django 5.0.6 on 2024-07-04 09:48

import main.models.generics
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_content_title_kk_content_title_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filecontent',
            options={'ordering': ('-index',), 'verbose_name': 'File content', 'verbose_name_plural': 'File contents'},
        ),
        migrations.AddField(
            model_name='filecontent',
            name='file_kk',
            field=models.FileField(null=True, upload_to=main.models.generics.FileContent.file_path, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='filecontent',
            name='file_ru',
            field=models.FileField(null=True, upload_to=main.models.generics.FileContent.file_path, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='filecontent',
            name='title_kk',
            field=models.TextField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='filecontent',
            name='title_ru',
            field=models.TextField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
