# Generated by Django 5.0.6 on 2024-07-04 11:33

import main.models.generics
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_filecontent_options_filecontent_file_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Chapter name'),
        ),
        migrations.AddField(
            model_name='content',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='filecontent',
            name='file_en',
            field=models.FileField(null=True, upload_to=main.models.generics.FileContent.file_path, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='filecontent',
            name='title_en',
            field=models.TextField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Topic name'),
        ),
    ]
