# Generated by Django 5.0.6 on 2024-07-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_content_description_en_content_description_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textcontent',
            name='title',
        ),
        migrations.RemoveField(
            model_name='textcontent',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='textcontent',
            name='title_kk',
        ),
        migrations.RemoveField(
            model_name='textcontent',
            name='title_ru',
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='filecontent',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
