# Generated by Django 5.0.6 on 2024-07-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_textcontent_title_remove_textcontent_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dropdown',
            field=models.BooleanField(default=False, verbose_name='Dropdown'),
        ),
        migrations.AddField(
            model_name='category',
            name='src',
            field=models.CharField(default='/', max_length=255, verbose_name='Source URL'),
        ),
        migrations.AddField(
            model_name='topic',
            name='dropdown',
            field=models.BooleanField(default=False, verbose_name='Dropdown'),
        ),
        migrations.AddField(
            model_name='topic',
            name='src',
            field=models.CharField(default='/', max_length=255, verbose_name='Source URL'),
        ),
    ]
