# Generated by Django 5.0.6 on 2024-07-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_category_dropdown_category_src_topic_dropdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='dropdown',
        ),
    ]
