# Generated by Django 5.0.6 on 2024-07-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_topic_options_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
