# Generated by Django 5.0.6 on 2024-07-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_topic_description_en_topic_description_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, verbose_name='Slug'),
        ),
    ]
