# Generated by Django 5.0.6 on 2024-07-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_category_slug_chapter_slug_content_slug_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='multiple_content',
            field=models.BooleanField(default=False, verbose_name='Multiple content'),
        ),
    ]
