# Generated by Django 5.0.6 on 2025-05-28 07:03

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headliner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='register/headliners/', validators=[main.validators.validate_poster], verbose_name='Poster')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('src', models.CharField(default='/', max_length=128, verbose_name='Source URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Is archive')),
            ],
            options={
                'verbose_name': 'Headliner',
                'verbose_name_plural': 'Headliners',
                'ordering': ('order',),
            },
        ),
    ]
