# Generated by Django 5.0.6 on 2025-05-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headliner',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='headliner',
            name='about_kk',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='headliner',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='headliner',
            name='title_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='headliner',
            name='title_kk',
            field=models.CharField(max_length=64, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='headliner',
            name='title_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Title'),
        ),
    ]
