# Generated by Django 5.0.6 on 2025-05-30 06:40

import register.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_department_faculty_program_division_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Partner name')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='register/public/partners/', validators=[register.validators.validate_file_size], verbose_name='Poster')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ('order',),
            },
        ),
        migrations.AlterField(
            model_name='headliner',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='register/public/headliners/', validators=[register.validators.validate_poster], verbose_name='Poster'),
        ),
    ]
