# Generated by Django 5.0.6 on 2025-06-24 04:44

import django.db.models.deletion
import main.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_partner_alter_headliner_poster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='docs_grid',
        ),
        migrations.AlterField(
            model_name='division',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='register/university/division/avatars', validators=[main.validators.validate_logo], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='division',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='register/university/division/posters', validators=[main.validators.validate_poster], verbose_name='Poster'),
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='register/publics/public/posters/', validators=[main.validators.validate_poster], verbose_name='Poster')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_publics', to='register.department', verbose_name='Department')),
                ('division', models.ForeignKey(blank=True, help_text='Warning! This field is not relevant for faculties and departments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_publics', to='register.division', verbose_name='Division')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_publics', to='register.faculty', verbose_name='Faculty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Public',
                'verbose_name_plural': 'Publics',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='PublicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, verbose_name='Title')),
                ('file', models.FileField(blank=True, null=True, upload_to='register/publics/public/files/', validators=[main.validators.validate_file_size], verbose_name='File')),
                ('own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_files', to='register.public', verbose_name='News')),
            ],
            options={
                'verbose_name': 'Public file',
                'verbose_name_plural': 'Public files',
            },
        ),
    ]
