# Generated by Django 5.0.6 on 2025-06-24 05:21

import register.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_public_description_en_public_description_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headliner',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='register/public/headliners/', validators=[register.validators.validate_poster], verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='register/public/partners/', validators=[register.validators.validate_file_size], verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='public',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='register/publics/public/posters/', validators=[register.validators.validate_poster], verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='publicfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='register/publics/public/files/', validators=[register.validators.validate_file_size], verbose_name='File'),
        ),
    ]
