# Generated by Django 5.0.6 on 2025-11-08 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_category_content_filecontent_imagecontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('title_kk', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popup_contents', to='register.content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Popup content',
                'verbose_name_plural': 'Popup contents',
                'ordering': ('order',),
            },
        ),
    ]
