# Generated by Django 5.0.6 on 2025-11-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_popupcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
                ('label_kk', models.CharField(max_length=128, null=True, verbose_name='Label')),
                ('label_ru', models.CharField(max_length=128, null=True, verbose_name='Label')),
                ('label_en', models.CharField(max_length=128, null=True, verbose_name='Label')),
                ('url', models.URLField(verbose_name='URL')),
                ('new_tab', models.BooleanField(default=False, verbose_name='New tab')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ('order',),
            },
        ),
    ]
