# Generated by Django 5.0.6 on 2024-07-29 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('name_kk', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('slug', models.CharField(max_length=128, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='university/faculties/avatars', verbose_name='Image')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='university/faculties/posters', verbose_name='Poster')),
                ('faculty_type', models.CharField(choices=[('DEFAULT', 'Default'), ('INSTITUTE', 'Institute'), ('COLLEGE', 'College')], default='DEFAULT', max_length=16, verbose_name='Faculty type')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_ru', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_kk', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_en', models.TextField(blank=True, null=True, verbose_name='About')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('name_kk', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('slug', models.CharField(max_length=128, verbose_name='Slug')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_ru', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_kk', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_en', models.TextField(blank=True, null=True, verbose_name='About')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='university.faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='university/personals/', verbose_name='Image')),
                ('profession', models.CharField(max_length=128, verbose_name='Profession')),
                ('profession_ru', models.CharField(max_length=128, null=True, verbose_name='Profession')),
                ('profession_kk', models.CharField(max_length=128, null=True, verbose_name='Profession')),
                ('profession_en', models.CharField(max_length=128, null=True, verbose_name='Profession')),
                ('phone', models.CharField(default='+7', max_length=32, verbose_name='Phone')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_ru', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_kk', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_en', models.TextField(blank=True, null=True, verbose_name='About')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personals',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=64, null=True, verbose_name='Name')),
                ('name_kk', models.CharField(max_length=64, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=64, null=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=64, verbose_name='Slug')),
                ('departments', models.ManyToManyField(related_name='programs', to='university.department', verbose_name='Departments')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='Code')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('name_kk', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='university.program', verbose_name='Program')),
            ],
        ),
    ]
