# Generated by Django 5.0.6 on 2024-07-26 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('slug', models.CharField(max_length=128, verbose_name='Slug')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('slug', models.CharField(max_length=128, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='university/faculties/avatars', verbose_name='Image')),
                ('poster', models.ImageField(upload_to='university/faculties/posters', verbose_name='Poster')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.RenameModel(
            old_name='ProgramItem',
            new_name='Specialty',
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='university.department', verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='university.faculty', verbose_name='Faculty'),
        ),
    ]
