# Generated by Django 5.0.6 on 2024-07-31 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_program_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Specialty', 'verbose_name_plural': 'Specialties'},
        ),
    ]
