# Generated by Django 5.0.6 on 2024-07-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_department_faculty_rename_programitem_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_type',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('INSTITUTE', 'Institute'), ('COLLEGE', 'College')], default='DEFAULT', max_length=16, verbose_name='Faculty type'),
        ),
    ]
