# Generated by Django 5.0.6 on 2024-07-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_department_about_en_department_about_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='university/faculties/avatars', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='university/faculties/posters', verbose_name='Poster'),
        ),
    ]
