# Generated by Django 5.0.6 on 2024-08-12 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('author', models.CharField(max_length=128, verbose_name='Author')),
                ('file', models.FileField(blank=True, null=True, upload_to='university/faculties/projects/', verbose_name='File')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='university.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
