# Generated by Django 5.0.6 on 2024-07-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_alter_faculty_image_alter_faculty_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
    ]
