# Generated by Django 5.0.6 on 2024-08-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_project_delete_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='project',
            name='author_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='project',
            name='author_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
    ]
