# Generated by Django 5.0.6 on 2024-07-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_specialty_name_en_specialty_name_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='department',
        ),
    ]
