# Generated by Django 5.0.6 on 2024-08-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_project_author_en_project_author_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Phone'),
        ),
    ]
