# Generated by Django 5.0.6 on 2024-07-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_remove_program_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='departments',
            field=models.ManyToManyField(related_name='programs', to='university.department', verbose_name='Departments'),
        ),
    ]
