# Generated by Django 5.0.6 on 2024-08-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_remove_personal_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='program',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='department',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
