# Generated by Django 5.0.6 on 2024-07-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='phone',
            field=models.CharField(default='+7', max_length=32, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='profession',
            field=models.CharField(max_length=128, verbose_name='Profession'),
        ),
    ]
