# Generated by Django 5.0.6 on 2024-08-15 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_remove_specialty_program_remove_specialty_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('slug', models.SlugField(max_length=64, verbose_name='Slug')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='university.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='FacultySpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='Code')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='university.facultyprogram', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
            },
        ),
    ]
