# Generated by Django 5.0.6 on 2024-07-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_personal_phone_alter_personal_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='personal',
            name='about_kk',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='personal',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='personal',
            name='profession_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='personal',
            name='profession_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='personal',
            name='profession_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Profession'),
        ),
    ]
