# Generated by Django 5.0.6 on 2024-08-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_facultyprogram_facultyspecialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprogram',
            name='name_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='facultyprogram',
            name='name_kk',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='facultyprogram',
            name='name_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='facultyspecialty',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='facultyspecialty',
            name='name_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='facultyspecialty',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
    ]
