# Generated by Django 5.0.6 on 2024-08-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_facultyprogram_name_en_facultyprogram_name_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='p_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('MANAGEMENT', 'Management')], default='MANAGEMENT', max_length=128, verbose_name='Personal type'),
        ),
    ]
