# Generated by Django 5.0.6 on 2024-09-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_personal_p_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='user',
        ),
        migrations.AddField(
            model_name='personal',
            name='full_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Full name'),
        ),
    ]
