# Generated by Django 5.0.6 on 2024-09-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_remove_personal_user_personal_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='personal',
            name='full_name_kk',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='personal',
            name='full_name_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Full name'),
        ),
    ]
