# Generated by Django 5.0.6 on 2024-09-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0015_personal_full_name_en_personal_full_name_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='university/faculties/avatars', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='department',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='university/faculties/posters', verbose_name='Poster'),
        ),
    ]
