# Generated by Django 5.0.6 on 2024-09-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_department_image_department_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprogram',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
