# Generated by Django 5.0.6 on 2024-10-03 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_alter_facultyprogram_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_personals', to='university.faculty', verbose_name='Faculty'),
        ),
        migrations.AddField(
            model_name='project',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_projects', to='university.faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_personals', to='university.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_projects', to='university.department', verbose_name='Department'),
        ),
        migrations.CreateModel(
            name='Success',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_achievements', to='university.department', verbose_name='Department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_achievements', to='university.faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Success',
                'verbose_name_plural': 'Achievements',
            },
        ),
    ]
