# Generated by Django 5.0.6 on 2024-10-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0021_alter_personal_options_personal_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='success',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='university/faculties/achievements/', verbose_name='File'),
        ),
    ]
