# Generated by Django 5.0.6 on 2024-10-17 05:13

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0022_success_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='university/faculties/avatars', validators=[main.validators.validate_file_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='department',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='university/faculties/posters', validators=[main.validators.validate_file_size], verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='university/faculties/avatars', validators=[main.validators.validate_file_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='university/faculties/posters', validators=[main.validators.validate_file_size], verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='university/personals/', validators=[main.validators.validate_file_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='university/faculties/projects/', validators=[main.validators.validate_file_size], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='success',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='university/faculties/achievements/', validators=[main.validators.validate_file_size], verbose_name='File'),
        ),
    ]
