# Generated by Django 5.0.6 on 2024-11-05 06:57

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0024_alter_department_image_alter_faculty_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='university/personals/', validators=[main.validators.validate_logo], verbose_name='Image'),
        ),
    ]
