# Generated by Django 5.0.6 on 2024-11-07 11:11

import django.db.models.deletion
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0026_alter_department_poster_alter_faculty_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('title_kk', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('author', models.CharField(max_length=128, verbose_name='Author')),
                ('author_kk', models.CharField(max_length=128, null=True, verbose_name='Author')),
                ('author_ru', models.CharField(max_length=128, null=True, verbose_name='Author')),
                ('author_en', models.CharField(max_length=128, null=True, verbose_name='Author')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_materials', to='university.department', verbose_name='Department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_materials', to='university.faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Edu material',
                'verbose_name_plural': 'Edu materials',
            },
        ),
        migrations.CreateModel(
            name='MaterialDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128, verbose_name='Name')),
                ('caption_kk', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('caption_ru', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('caption_en', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('file', models.FileField(blank=True, null=True, upload_to='university/faculties/materials/', validators=[main.validators.validate_file_size], verbose_name='File')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.material', verbose_name='Edu material')),
            ],
            options={
                'verbose_name': 'Edu material',
                'verbose_name_plural': 'Edu materials',
            },
        ),
    ]
