# Generated by Django 5.0.6 on 2024-11-07 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0027_material_materialdocs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdocs',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_files', to='university.material', verbose_name='Edu material'),
        ),
    ]
