# Generated by Django 5.0.6 on 2024-11-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0028_alter_materialdocs_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date created'),
        ),
    ]
