# Generated by Django 5.0.6 on 2024-11-11 04:44

import django.db.models.deletion
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0029_alter_material_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('docs_type', models.CharField(choices=[('SCI', 'Scientific internship'), ('RD', 'Regulatory documents'), ('CON', 'Contracts')], default='SCI', max_length=128, verbose_name='Document type')),
                ('docs_grid', models.CharField(choices=[('GRID', 'Grid'), ('COL', 'Column')], default='GRID', max_length=128, verbose_name='Document grid')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_documents', to='university.department', verbose_name='Department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_documents', to='university.faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128, verbose_name='Name')),
                ('file', models.FileField(blank=True, null=True, upload_to='university/faculties/documents/', validators=[main.validators.validate_file_size], verbose_name='File')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='university.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Document file',
                'verbose_name_plural': 'Document files',
            },
        ),
    ]
