# Generated by Django 5.0.6 on 2024-11-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0030_document_documentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='caption_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='caption_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='caption_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
    ]
