# Generated by Django 5.0.6 on 2024-11-11 07:08

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0031_document_title_en_document_title_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='docs_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title_kk',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='caption_en',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='caption_kk',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='caption_ru',
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='Hi!', max_length=128, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='document',
            name='name_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='document',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentfile',
            name='title',
            field=models.CharField(default=datetime.datetime(2024, 11, 11, 7, 8, 23, 998197, tzinfo=datetime.timezone.utc), max_length=128, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentfile',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='title_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
    ]
