# Generated by Django 5.0.6 on 2024-11-13 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0032_remove_document_docs_type_remove_document_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('slug', models.SlugField(max_length=128, verbose_name='Slug')),
                ('div_type', models.CharField(choices=[('DEFAULT', 'Division'), ('DEPARTMENT', 'Department'), ('MANAGEMENT', 'Management')], default='DEFAULT', verbose_name='Division type')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='university.division', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ('order',),
            },
        ),
    ]
