# Generated by Django 5.0.6 on 2024-11-14 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0034_division_about_en_division_about_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='div_type',
            field=models.CharField(choices=[('DEFAULT', 'Division'), ('DEPARTMENT', 'Department division'), ('MANAGEMENT', 'Management division')], default='DEFAULT', verbose_name='Division type'),
        ),
        migrations.AlterField(
            model_name='division',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='university.division', verbose_name='Parent division'),
        ),
    ]
