# Generated by Django 5.0.6 on 2024-11-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0035_alter_division_div_type_alter_division_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About the department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='About the department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='about_kk',
            field=models.TextField(blank=True, null=True, verbose_name='About the department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='About the department'),
        ),
        migrations.AlterField(
            model_name='division',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About the division'),
        ),
        migrations.AlterField(
            model_name='division',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='About the division'),
        ),
        migrations.AlterField(
            model_name='division',
            name='about_kk',
            field=models.TextField(blank=True, null=True, verbose_name='About the division'),
        ),
        migrations.AlterField(
            model_name='division',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='About the division'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About the faculty'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='About the faculty'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='about_kk',
            field=models.TextField(blank=True, null=True, verbose_name='About the faculty'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='About the faculty'),
        ),
    ]
