# Generated by Django 5.0.6 on 2024-11-14 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0036_alter_department_about_alter_department_about_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Warning! This field is not relevant for faculties and departments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_documents', to='university.division', verbose_name='Division'),
        ),
        migrations.AddField(
            model_name='personal',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Warning! This field is not relevant for faculties and departments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_personals', to='university.division', verbose_name='Division'),
        ),
        migrations.AddField(
            model_name='success',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Warning! This field is not relevant for faculties and departments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_achievements', to='university.division', verbose_name='Division'),
        ),
    ]
