# Generated by Django 5.0.6 on 2024-11-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0037_document_division_personal_division_success_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='p_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('MANAGEMENT', 'Management'), ('EMPLOYEE', 'Employee')], default='MANAGEMENT', max_length=128, verbose_name='Personal type'),
        ),
    ]
