# Generated by Django 5.0.6 on 2024-11-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0038_alter_personal_p_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='p_type',
            field=models.CharField(choices=[('Faculty', [('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('MANAGEMENT', 'Management')]), ('Division', [('EMPLOYEE', 'Employee')])], default='FACULTY', max_length=128, verbose_name='Personal type'),
        ),
    ]
