# Generated by Django 5.0.6 on 2024-11-25 10:21

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0039_alter_personal_p_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyspecialty',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='university/faculties/programs/', validators=[main.validators.validate_file_size], verbose_name='File'),
        ),
    ]
