# Generated by Django 5.0.6 on 2024-11-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0040_facultyspecialty_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyspecialty',
            name='file',
        ),
    ]
