# Generated by Django 5.0.6 on 2024-12-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0041_remove_facultyspecialty_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='p_type',
            field=models.CharField(choices=[('Faculty', [('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('MANAGEMENT', 'Management')]), ('Division', [('EMPLOYEE', 'Employee')])], default='STUDENT', max_length=128, verbose_name='Personal type'),
        ),
    ]
