# Generated by Django 5.0.6 on 2024-12-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0042_alter_personal_p_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyspecialty',
            name='url',
            field=models.URLField(blank=True, max_length=128, null=True, verbose_name='URL'),
        ),
    ]
