# Generated by Django 5.0.6 on 2024-12-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0047_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='author',
        ),
        migrations.RemoveField(
            model_name='material',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='material',
            name='author_kk',
        ),
        migrations.RemoveField(
            model_name='material',
            name='author_ru',
        ),
    ]
