# Generated by Django 5.0.6 on 2024-12-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0048_remove_material_author_remove_material_author_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.personal', verbose_name='Author'),
        ),
    ]
