# Generated by Django 5.0.6 on 2025-01-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0050_alter_material_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='div_type',
            field=models.CharField(choices=[('DEFAULT', 'Division/Center'), ('DEPARTMENT', 'Department division'), ('MANAGEMENT', 'Management division')], default='DEFAULT', verbose_name='Division type'),
        ),
    ]
