# Generated by Django 5.0.6 on 2025-01-21 06:19

import django.db.models.deletion
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0051_alter_division_div_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='university/faculties/avatars', validators=[main.validators.validate_logo], verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='division',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='university/faculties/posters', validators=[main.validators.validate_poster], verbose_name='Poster'),
        ),
        migrations.AddField(
            model_name='facultyprogram',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='university.faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='division',
            name='div_type',
            field=models.CharField(choices=[('div', 'Division/Center'), ('department', 'Department'), ('management', 'Management')], default='div', verbose_name='Division type'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_type',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('institute', 'Institute'), ('college', 'College')], default='faculty', max_length=16, verbose_name='Faculty type'),
        ),
        migrations.AlterField(
            model_name='facultyprogram',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='university.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='p_type',
            field=models.CharField(choices=[('Faculty', [('deans_office', "Dean's office"), ('department_manage', 'Department management'), ('teacher', 'Teacher/Professors'), ('student', 'Active students')]), ('Division', [('head', 'Head of Department'), ('employee', 'Employee')])], default='student', max_length=128, verbose_name='Personal type'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='profession',
            field=models.CharField(max_length=128, verbose_name='Profession/Activity'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='profession_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Profession/Activity'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='profession_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Profession/Activity'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='profession_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Profession/Activity'),
        ),
    ]
