# Generated by Django 5.0.6 on 2025-01-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0053_alter_division_div_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Phone'),
        ),
    ]
