# Generated by Django 5.0.6 on 2025-02-03 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0054_personal_email_alter_personal_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyspecialty',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='university.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='facultyspecialty',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='university.faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='facultyspecialty',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_items', to='university.facultyprogram', verbose_name='Program'),
        ),
    ]
