# Generated by Django 5.0.6 on 2025-02-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0055_facultyspecialty_department_facultyspecialty_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprogram',
            name='department',
        ),
        migrations.RemoveField(
            model_name='facultyprogram',
            name='faculty',
        ),
    ]
