# Generated by Django 5.0.6 on 2025-02-04 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0057_alter_faculty_options_department_order_faculty_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='order',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='order',
        ),
    ]
