# Generated by Django 5.0.6 on 2025-02-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0058_alter_faculty_options_remove_department_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ('order',), 'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AddField(
            model_name='faculty',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
