# Generated by Django 5.0.6 on 2025-03-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0059_alter_faculty_options_faculty_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfile',
            options={'ordering': ('order',), 'verbose_name': 'Document file', 'verbose_name_plural': 'Document files'},
        ),
        migrations.AddField(
            model_name='documentfile',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
