# Generated by Django 5.0.6 on 2025-03-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0060_alter_documentfile_options_documentfile_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfile',
            options={'ordering': ('-order',), 'verbose_name': 'Document file', 'verbose_name_plural': 'Document files'},
        ),
    ]
